### ISSUE TITLE
Libreelec kodi 18 - first 2 minutes playing via netflix addon are black

### ISSUE THREAD

**Issue by DanielGabris** [emilsvennesson/script.module.inputstreamhelper#475] opened 2021-12-18 18:04 UTC
Hello, 

when playing movies via netflix addon, first 2 minutes  of avery movie are black (with sound), ater then, movie continue without issue. 

any idea how to fix this?

Inputstreamer helper 0.5.8
inputstreamer adaptive 2.3.17
widevine CDM 4.10.1679

thanks

Daniel

**Comment by horstle** [comment] 2021-12-19 19:01
Update inputstream.adaptive. Your version was released on april 2019, the newest version (for Leia: 2.4.8) is from july this year.

**Comment by DanielGabris** [comment] 2021-12-20 12:54
I have leila 18.2 (no newer is availabla under raspbian debian and it  the inputstreamer adaptive is updates (latest available there is 2.3.17)

**Comment by horstle** [comment] 2021-12-21 10:07
In the title you said you are using LibreELEC. Apparently now you are using Raspbian Stretch. In that case you should update your system to Buster or Bullseye.

Anyway, since the issue is not related to inputstreamhelper, I'm going to close this. If the issue persists, please ask on the Kodi or Raspberry Pi forums.

**Closed by horstle** 2021-12-21 10:07 UTC
