### ISSUE TITLE
Internal error when trying to start movie on RPi-Kodi-Netflix

### ISSUE THREAD

**Issue by WernerBleisteiner** [emilsvennesson/script.module.inputstreamhelper#503] opened 2022-03-19 17:40 UTC
Since last week I encounter this issue when trying to watch a movie on LE 9.2.8 Kodi 18.9 on a rpi3. Before all went smooth.
Any suggestions or workaround. Couldn't find any updates with fixes so far.
Thanks.
![image](https://user-images.githubusercontent.com/22868982/159132231-f1894d47-ae27-404d-877c-bc0672dd2088.jpeg)

**Comment by AreaScout** [comment] 2022-03-19 19:41
Same here on ODROID XU4, Kodi Leia

**Comment by horstle** [comment] 2022-03-19 20:26
Probably duplicate of #495 

Please try the testbuilds from here: https://github.com/emilsvennesson/script.module.inputstreamhelper/issues/497#issuecomment-1068239609

**Closed by horstle** 2022-03-19 20:26 UTC

**Comment by WernerBleisteiner** [comment] 2022-03-19 21:00
Brillant! Thanks!
