### ISSUE TITLE
LooseVersion instance has no attribute 'version'

### ISSUE THREAD

**Issue by npmstart-pray** [emilsvennesson/script.module.inputstreamhelper#351] opened 2020-05-15 03:15 UTC
so there I was 15 minutes ago watching netflix, and when I hit Watch when it came up in Up Next, I got a message about WideVine not being installed, and then this error came up, telling me to report it.
Ant idea what went wrong and/or how to fix it?
4GB RasPi 4, current xbian k5.4.38  kodi 18.6 buster current inpustream helper
I'll go digging for the log and post here.

**Comment by zurrealist** [comment] 2020-05-15 06:07
I'm running into this same issue. I'm on Kodi 18.6, running LibreELEC 9.2.1 on a RasPi 4.
Netflic worked fine yesterday, but today I'm getting an error that "An error occurred while installing Widevine CDM" and to post here. The following message reads "The operation has been cancelled. InputStream Helper has been generated an internal error: LooseVersion instance has no attribute 'version'"
Log should be at:
https://paste.kodi.tv/osewufiyoc

**Comment by npmstart-pray** [comment] 2020-05-15 06:24
I was hoping for a fix in the documentation, but no such luck. Part of me wonders if it went looking for (or was notified of) a widevine update and failed.

**Comment by zurrealist** [comment] 2020-05-15 06:55
I did try reinstalling both the Netflix add-on and the InputStream Adaptive add-on with no luck.

**Comment by horstle** [comment] 2020-05-15 07:28
Anyone experiencing this issue or #352 :

If you could previously watch videos, you can simply disable inputstreamhelper for now. To do that, go to the Addons section, open Inputstream Helper and enable "Disabled". After that your videos should start as before.

**Comment by horstle** [comment] 2020-05-15 07:32
The problem is, that the recovery.conf contains nothing. Hopefully Google fixes this, soon. But in the long run, we should analyze the "Chrome OS recovery utility", assuming that doesn't use the recovery.conf.

**Comment by horstle** [comment] 2020-05-15 08:00
Ok, the utility uses https://dl.google.com/dl/edgedl/chromeos/recovery/recovery.json or https://dl.google.com/dl/edgedl/chromeos/recovery/onhub_recovery.json.

The onhub_recovery.json only contains ARKHAM, WHIRLWIND and GALE, which afaik are all incompatible.
The recovery.json is completely empty. I guess some Google internal script which should update recovery.conf and recovery.json failed and created empty files instead.

**Comment by dagwieers** [comment] 2020-05-15 10:05
InputStreamHelper is supposed to leave a working setup intact in case of issues with the upgrade, so this is an oversight in the design. If recovery.json is empty, or if your system is not found, but you have a (working?) Widvine CDM it ought to step down and leave as-is.

The update process is important because your (previously working?) Widevine CDM may no longer work due to changes at Widevine, so we need to regularly update it, but not at the expense of breaking a working system.

What we would like to do in the future is turn this around. Rather than check before playback whether an update is required, we would like to learn from InputStream Adaptive if playback failed due to Widevine issues (onPlayBackError), and trigger an update as because of these (specific) IA errors.

This would ensure that a working system is used as long as its Widevine CDM is supported and only updates when it is no longer supported. At this moment IA does not report playback errors, so we cannot implement this. I am also not sure if this new design will work well in practice, but theoretically it would make things easier.

**Comment by npmstart-pray** [comment] 2020-05-15 16:57
>Anyone experiencing this issue or #352 : ...

@horstle upon trying your suggestion I get a “but these other addons use ISH, so it can’t be disabled” message. What about Uninstalling?

**Comment by horstle** [comment] 2020-05-15 17:54
@npmstart-pray You should not disable the addon itself. As I explained, you should open the Inputstream Helper addon (opening the addon will actually open its settings page), where you should enable the option "Disable".

**Comment by npmstart-pray** [comment] 2020-05-15 18:12
What does the other one do, and why aren’t they connected?

**Comment by horstle** [comment] 2020-05-15 18:25
As you already realized, you can't disable inputstreamhelper, because it is executed by other addons. With the "Disable" option from the settings page enabled, inputstreamhelper will not do any checks, but simply tell the addon calling it, that everything is fine (even if it isn't, which is why that option should in general be used with caution).

**Comment by horstle** [comment] 2020-05-15 19:25
I assumed this would be fixed within a few hours. Since that's not the case I created a temporary fix, but couldn't test it yet.
If you want to try it, here is the zip: 
[script.module.inputstreamhelper-0.4.7-conf_temp_fix-65e864b.zip](https://github.com/emilsvennesson/script.module.inputstreamhelper/files/4636759/script.module.inputstreamhelper-0.4.7-conf_temp_fix-65e864b.zip)

If you want to have a look at the changes, you can do so here: https://github.com/horstle/script.module.inputstreamhelper/tree/conf_temp_fix

**Comment by maste9** [comment] 2020-05-15 21:02
After having the same problems with a recently installed LibreELEC on RPi4 I installed your fix.

Now I receive the Add-on error 
> The operation has been cancelled. InputStream Helper has generated an internal error:
u'hwidmatch'

**Comment by carpioldc** [comment] 2020-05-15 21:05
Hi! I tried it, but now the error is somewhere else. I checked and the contents of https://dl.google.com/dl/edgedl/chromeos/recovery/recovery.json have changed from

```
recovery_tool_version=0.9.2
recovery_tool_linux_version=0.9.2
recovery_tool_update=


```
to just `[]`. So it seems they're on it. Here's the trace:

````
2020-05-15 22:47:59.679 T:1769992928   DEBUG: [script.module.inputstreamhelper] Request URL: https://dl.google.com/dl/edgedl/chromeos/recovery/recovery.conf
2020-05-15 22:47:59.779 T:1769992928   DEBUG: [script.module.inputstreamhelper] Response code: 200
2020-05-15 22:47:59.780 T:1769992928   DEBUG: [script.module.inputstreamhelper] Find best ARM image to use from the Chrome OS recovery.conf
2020-05-15 22:47:59.781 T:1769992928   ERROR: [plugin.video.netflix (1)] Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/navigation/player.py", line 162, in get_inputstream_listitem
                                                inputstream_ready = is_helper.check_inputstream()
                                              File "/home/osmc/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 415, in check_inputstream
                                                return self._check_drm()
                                              File "/home/osmc/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 370, in _check_drm
                                                return self.install_widevine()
                                              File "/home/osmc/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 34, in clean_before_after
                                                result = func(self, *args, **kwargs)
                                              File "/home/osmc/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 224, in install_widevine
                                                result = install_widevine_arm(backup_path())
                                              File "/home/osmc/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/widevine/arm.py", line 152, in install_widevine_arm
                                                arm_device = select_best_chromeos_image(devices)
                                              File "/home/osmc/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/widevine/arm.py", line 82, in select_best_chromeos_image
                                                if '^{0} '.format(arm_hwid) in device['hwidmatch']:
                                            KeyError: u'hwidmatch'
2020-05-15 22:47:59.811 T:1915364912   DEBUG: ------ Window Init (DialogConfirm.xml) ------
2020-05-15 22:48:01.228 T:1894773472   DEBUG: CLibInputKeyboard::ProcessKey - using delay: 500ms repeat: 50ms
````

**Comment by frudolph77** [comment] 2020-05-15 21:13
I've tried this fix, but it leads to an other one
The EULA was downloaded and after confirming the update/installation crashes instantly:

```2020-05-15 23:08:31.651 T:1545769856 WARNING: Previous line repeats 1 times.
2020-05-15 23:08:31.651 T:1545769856  NOTICE: [script.module.inputstreamhelper] Recursively create directory '/storage/.kodi/userdata/addon_data/script.module.inputstream
helper/temp'.
2020-05-15 23:08:31.652 T:1545769856  NOTICE: [script.module.inputstreamhelper] Create directory '/storage/.kodi/userdata/addon_data/script.module.inputstreamhelper/temp/
mnt'.
2020-05-15 23:08:31.682 T:1545769856  NOTICE: [script.module.inputstreamhelper] Recursively create directory '/storage/.kodi/cdm'.
2020-05-15 23:08:31.686 T:1545769856  NOTICE: Previous line repeats 1 times.
2020-05-15 23:08:31.686 T:1545769856 WARNING: [script.module.inputstreamhelper] Widevine CDM is not installed.
2020-05-15 23:08:31.689 T:1545769856  NOTICE: [script.module.inputstreamhelper] Recursively create directory '/storage/.kodi/cdm'.
2020-05-15 23:08:31.691 T:1545769856  NOTICE: [script.module.inputstreamhelper] Recursively create directory '/storage/.kodi/userdata/addon_data/script.module.inputstream
helper/temp'.
2020-05-15 23:08:36.949 T:1545769856  NOTICE: Previous line repeats 1 times.
2020-05-15 23:08:36.949 T:1545769856  NOTICE: [script.module.inputstreamhelper] Recursively create directory '/storage/.kodi/userdata/addon_data/script.module.inputstream
helper/backup'.
2020-05-15 23:08:37.138 T:1545769856   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: u'hwidmatch'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/default.py", line 8, in <module>
                                                run(sys.argv)
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/api.py", line 14, in run
                                                widevine_install()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/api.py", line 42, in widevine_install
                                                Helper('mpd', drm='widevine').install_widevine()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 34, in clean_before_aft
er
                                                result = func(self, *args, **kwargs)
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 224, in install_widevin
e
                                                result = install_widevine_arm(backup_path())
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/widevine/arm.py", line 152, in install_wid
evine_arm
                                                arm_device = select_best_chromeos_image(devices)
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/widevine/arm.py", line 82, in select_best_
chromeos_image
                                                if '^{0} '.format(arm_hwid) in device['hwidmatch']:
                                            KeyError: u'hwidmatch'
                                            -->End of Python script error report<--```

**Comment by Denyerec** [comment] 2020-05-15 21:28
Found this issue as my Kodi (18.4 Leia on Pi via Librelec) stopped playing Netflix content a few days ago.
Been fiddling around trying to get inputstreamhelper to reinstall Widevine and mine is dying, very similarly to the previous poster, here:

2020-05-15 23:08:31.689 T:1545769856  NOTICE: [script.module.inputstreamhelper] Recursively create directory '/storage/.kodi/cdm'.

with a "ERROR: No such file or directory: '/storage/.kodi/cdm' "

Hope to get to the bottom of it soon as the kids have gone mental :D

**Comment by horstle** [comment] 2020-05-15 21:32
Yes, sorry. I had missed one line. This should work:
[script.module.inputstreamhelper-0.4.7-conf_temp_fix-f7115d4.zip](https://github.com/emilsvennesson/script.module.inputstreamhelper/files/4637198/script.module.inputstreamhelper-0.4.7-conf_temp_fix-f7115d4.zip)

**Comment by Denyerec** [comment] 2020-05-15 21:34
@horstle - For a complete n00b, how would I go about implementing your fixed file ? I'm running Kodi Leia via LibreElec on Pi, so don't appear to have access to shell :/

**Comment by npmstart-pray** [comment] 2020-05-15 21:35
I tried 4, 5, maybe 6 times to install WideVine before it actually did, successfully. I’ve disabled ISH from its settings and Netflix is back to working.

**Comment by horstle** [comment] 2020-05-15 21:38
Copy the zip to a USB drive, plug it into your Pi and in the Addons section choose "install from zip". It will probably tell you to change a setting, enable that. Afterwards try again and choose the zip from the usb drive.

**Comment by Denyerec** [comment] 2020-05-15 22:07
> Copy the zip to a USB drive, plug it into your Pi and in the Addons section choose "install from zip". It will probably tell you to change a setting, enable that. Afterwards try again and choose the zip from the usb drive. Afterwards you may have to restart Kodi.

Perfect, it's back to working, helper disabled for now - Thankyou so much!

**Comment by horstle** [comment] 2020-05-15 22:17
Aaand the recovery.conf is back...
Everything should be back to normal now.

**Comment by mediaminister** [comment] 2020-05-16 04:57
Google fixed it: https://support.google.com/chromebook/thread/46853544
So this can be closed.

**Closed by mediaminister** 2020-05-16 04:57 UTC
Labels: arm, bug, widevine

**Comment by zurrealist** [comment] 2020-05-16 05:24
Thanks! Disabling worked! But not quite as expected.

I got a prompt saying that InputStream needed to be enabled. I did so and then had the option to update Widevine CDN. I ran the update, and then once it finished, I was back to working as normal.

**Comment by npmstart-pray** [comment] 2020-05-16 16:48
Yup, back to normal here too. It even properly cleaned up after itself. 
Bad Google!  Or is it Alphabet?
