### ISSUE TITLE
Error when running remove_widevine from settings if inputstream.adaptive is disabed

### ISSUE THREAD

**Issue by flubshi** [emilsvennesson/script.module.inputstreamhelper#138] opened 2019-08-31 11:12 UTC
I installed the latest version of script.module.inputstreamhelper (ff28f54) for testing (#113). I did not notice that the plugin inputstream.adaptive was disabled when trying to run "Remove Widevine CDM library..." from settings.

To reproduce:
- install latest version of script.module.inputstreamhelper
- (install widevine)
- disable inputstream.adaptive
- run "Remove Widevine CDM library..." from settings

![image](https://user-images.githubusercontent.com/4031504/64063098-21225b00-cbf0-11e9-8e5e-951577da2ce7.png)

The following error occurs:
![image](https://user-images.githubusercontent.com/4031504/64063107-37c8b200-cbf0-11e9-85f9-ec51888352c6.png)

Related debug log:

```
019-08-31 12:52:58.873 T:140179872409344   DEBUG: [script.module.inputstreamhelper][routing] Dispatching to 'widevine_remove', args: {}
2019-08-31 12:52:58.873 T:140179872409344   DEBUG: [script.module.inputstreamhelper-0.4.0]: Platform information: ('Linux', 'username', '5.2.9-arch1-1-ARCH', '#1 SMP PREEMPT Fri Aug 16 11:29:43 UTC 2019', 'x86_64', '')
2019-08-31 12:52:58.885 T:140179872409344   ERROR: EXCEPTION: Unknown addon id 'inputstream.adaptive'.
2019-08-31 12:52:58.886 T:140179872409344   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.RuntimeError'>
                                            Error Contents: Unknown addon id 'inputstream.adaptive'.
                                            Traceback (most recent call last):
                                              File "/home/username/.kodi/addons/script.module.inputstreamhelper/addon.py", line 48, in <module>
                                                plugin.run(sys.argv)
                                              File "/home/username/.kodi/addons/script.module.routing/lib/routing.py", line 115, in run
                                                self._dispatch(path)
                                              File "/home/username/.kodi/addons/script.module.routing/lib/routing.py", line 126, in _dispatch
                                                view_func(**kwargs)
                                              File "/home/username/.kodi/addons/script.module.inputstreamhelper/addon.py", line 44, in widevine_remove
                                                Helper('mpd', drm='widevine').remove_widevine()
                                              File "/home/username/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper.py", line 699, in remove_widevine
                                                widevinecdm = self._widevine_path()
                                              File "/home/username/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper.py", line 181, in _widevine_path
                                                widevine_path = os.path.join(cls._ia_cdm_path(), widevine_cdm_filename)
                                              File "/home/username/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper.py", line 154, in _ia_cdm_path
                                                addon = xbmcaddon.Addon('inputstream.adaptive')
                                            RuntimeError: Unknown addon id 'inputstream.adaptive'.
                                            -->End of Python script error report<--
2019-08-31 12:52:58.886 T:140179872409344   DEBUG: onExecutionDone(3, /home/username/.kodi/addons/script.module.inputstreamhelper/addon.py)
2019-08-31 12:52:58.899 T:140181215316672   DEBUG: ------ Window Init (DialogNotification.xml) ------
2019-08-31 12:52:58.902 T:140179872409344    INFO: Python interpreter stopped
2019-08-31 12:52:58.902 T:140179872409344   DEBUG: Thread LanguageInvoker 140179872409344 terminating
2019-08-31 12:53:04.622 T:140181215316672   DEBUG: ------ Window Deinit (DialogNotification.xml) ------

```

**Comment by dagwieers** [comment] 2019-08-31 11:13
This is a duplicate of #131

**Closed by dagwieers** 2019-08-31 11:13 UTC

**Comment by flubshi** [comment] 2019-08-31 11:14
sorry for duplicate

**Comment by dagwieers** [comment] 2019-08-31 11:18
No worries :-)
