### ISSUE TITLE
Kodi crashes on Video load - no debug Infos

### ISSUE THREAD

**Issue by blankschyn** [emilsvennesson/script.module.inputstreamhelper#254] opened 2020-02-03 19:27 UTC
Hi,
hopefully this is the right place for this problem:
After starting a skygo Video, kodi crashes without a warning. I set the debug log level and this is the output:

 2020-02-03 20:23:04.895 T:139862657201920   DEBUG: [script.module.inputstreamhelper]: There are no missing Widevine libraries! :-)
2020-02-03 20:23:04.895 T:139862657201920   DEBUG: [script.module.inputstreamhelper]: Widevine update check was made on 2020-02-03T19:22:53
2020-02-03 20:23:04.992 T:139862657201920   DEBUG: [Sky Go] User still logged in
2020-02-03 20:23:05.068 T:139862657201920    INFO: CPythonInvoker(10, /home/maxblank/.kodi/addons/plugin.video.skygo.de/default.py): script successfully run
2020-02-03 20:23:05.082 T:139862795016896   DEBUG: ------ Window Deinit (DialogBusy.xml) ------
2020-02-03 20:23:05.082 T:139860946380544   DEBUG: Thread scriptobs 139860946380544 terminating
2020-02-03 20:23:05.085 T:139862795016896   DEBUG: CPlayerCoreFactory::GetPlayers(http://skywebvod-s.akamaihd.net/ondemand/Production/de_at/movies/F30055371____100332001/F30055371____100332001.ism/Manifest)
2020-02-03 20:23:05.085 T:139862795016896   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: system rules
2020-02-03 20:23:05.085 T:139862795016896   DEBUG: CPlayerSelectionRule::GetPlayers: matches rule: system rules
2020-02-03 20:23:05.085 T:139862795016896   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: mms/udp
2020-02-03 20:23:05.085 T:139862795016896   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: lastfm/shout
2020-02-03 20:23:05.086 T:139862795016896   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: rtmp
2020-02-03 20:23:05.086 T:139862795016896   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: rtsp
2020-02-03 20:23:05.086 T:139862795016896   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: streams
2020-02-03 20:23:05.086 T:139862795016896   DEBUG: CPlayerSelectionRule::GetPlayers: matches rule: streams
2020-02-03 20:23:05.086 T:139862795016896   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: aacp/sdp
2020-02-03 20:23:05.086 T:139862795016896   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: mp2
2020-02-03 20:23:05.086 T:139862795016896   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: dvd
2020-02-03 20:23:05.086 T:139862795016896   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: dvdimage
2020-02-03 20:23:05.086 T:139862795016896   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: sdp/asf
2020-02-03 20:23:05.086 T:139862795016896   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: nsv
2020-02-03 20:23:05.086 T:139862795016896   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: radio
2020-02-03 20:23:05.086 T:139862795016896   DEBUG: CPlayerCoreFactory::GetPlayers: matched 0 rules with players
2020-02-03 20:23:05.086 T:139862795016896   DEBUG: CPlayerCoreFactory::GetPlayers: adding videodefaultplayer (VideoPlayer)
2020-02-03 20:23:05.086 T:139862795016896   DEBUG: CPlayerCoreFactory::GetPlayers: for video=1, audio=0
2020-02-03 20:23:05.086 T:139862795016896   DEBUG: CPlayerCoreFactory::GetPlayers: for video=1, audio=1
2020-02-03 20:23:05.086 T:139862795016896   DEBUG: CPlayerCoreFactory::GetPlayers: added 1 players
2020-02-03 20:23:05.087 T:139862795016896   DEBUG: Radio UECP (RDS) Processor - new CDVDRadioRDSData
2020-02-03 20:23:05.087 T:139862795016896  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.skygo.de/<shortened>
2020-02-03 20:23:05.087 T:139862795016896    INFO: easy_acquire - Created session to http://skywebvod-s.akamaihd.net
2020-02-03 20:23:05.126 T:139862795016896   DEBUG: CCurlFile::GetMimeType - http://skywebvod-s.akamaihd.net/ondemand/Production/de_at/movies/F30055371____100332001/F30055371____100332001.ism/Manifest -> text/xml
2020-02-03 20:23:05.126 T:139862795016896   DEBUG: OnPlayBackStarted: CApplication::OnPlayBackStarted
2020-02-03 20:23:05.126 T:139860946380544   DEBUG: Thread VideoPlayer start, auto delete: false
2020-02-03 20:23:05.127 T:139860946380544  NOTICE: Creating InputStream
2020-02-03 20:23:05.127 T:139862636508928   DEBUG: Thread BackgroundLoader start, auto delete: false
2020-02-03 20:23:05.127 T:139860946380544   DEBUG: ADDON: Dll Initializing - InputStream Adaptive
2020-02-03 20:23:05.127 T:139860946380544   DEBUG: SECTION:LoadDLL(/usr/lib/kodi/addons/inputstream.adaptive/inputstream.adaptive.so.2.4.2)
2020-02-03 20:23:05.127 T:139860946380544   DEBUG: Loading: /usr/lib/kodi/addons/inputstream.adaptive/inputstream.adaptive.so.2.4.2

**Comment by mediaminister** [comment] 2020-02-03 19:45
I don't see an error in your log, so I don't have a clue what the problem is.
Please reboot you Kodi device, try again and post a full debug log if the problem persists.

**Comment by dagwieers** [comment] 2020-02-04 10:46
It is more likely that **inputstream.adaptive** is causing a crash like this.
Kodi can dump memory and log a stacktrace.

**Comment by dagwieers** [comment] 2020-02-25 00:57
No feedback, closing this issue.

**Closed by dagwieers** 2020-02-25 00:57 UTC
Labels: invalid, question
