### ISSUE TITLE
Playback issues using Widevine 4.10.2202.0 (eg. when using Binge)

### ISSUE THREAD

**Issue by Sil3ntKn1ght** [emilsvennesson/script.module.inputstreamhelper#430] opened 2021-03-27 07:24 UTC
Widows 10 - kodi v19 issue is running widevine 4.10.2202.0 Binge video while playing around two the five minutes in will drop out and you end back at the Binge selection.
running 4.10.1582.2 there are no issues videos play fine in Binge however 9au etc wont play without the latest version.
I can't or the life of me find the error to this in the log, its like a buffer drop out. 
Can not find anything in google to this issue.
I have tried everything to no avail.

**Comment by dagwieers** [comment] 2021-03-28 00:41
If it is a regression in the Widevine library, please roll back and disable InputStream Helper to avoid having it update uncontrolled. A future release, or backend fix may fix the issue in the future.

**Comment by matthuisman** [comment] 2021-04-14 21:05
@dagwieers 
are you hearing about any other issues with 4.10.2202.0 except for the above?

**Comment by dagwieers** [comment] 2021-04-15 12:56
No, I haven't heard of any other issues here. Maybe people have seen this issue and implemented the work-around. Or maybe they have reported it elsewhere. Or maybe this was a one-off.

**Comment by Sil3ntKn1ght** [comment] 2021-04-15 14:35
Binge won't play. crashes 

2021-04-15 22:33:31.549 T:13176    INFO <general>: CPythonInvoker(36, C:\Users\The Box\AppData\Roaming\Kodi\addons\slyguy.binge\default.py): script successfully run
2021-04-15 22:33:31.549 T:4696    ERROR <general>: CCurlFile::FillBuffer - Failed: Server returned nothing (no headers, no data)(52)
2021-04-15 22:33:31.549 T:4696    ERROR <general>: CCurlFile::Open failed with code 0 for http://127.0.0.1:52103/plugin://slyguy.binge/?_=license_request:
                                                   
2021-04-15 22:33:31.549 T:4696    ERROR <general>: AddOnLog: inputstream.adaptive: License server returned failure
2021-04-15 22:33:31.549 T:4696    ERROR <general>: AddOnLog: inputstream.adaptive: License update not successful (no keys)
2021-04-15 22:33:31.549 T:4696    ERROR <general>: AddOnLog: inputstream.adaptive: Initialize failed (SingleSampleDecrypter)
2021-04-15 22:33:31.584 T:4696    ERROR <general>: CVideoPlayer::OpenInputStream - error opening [plugin://slyguy.binge/?_=play&_play=1&id=31348&play_type=0&start_from=0]

**Comment by matthuisman** [comment] 2021-04-15 19:43
You've already posted that in the forums. Please dont repeat in multiple places. And please provide full debug logs

**Comment by dagwieers** [comment] 2021-06-15 00:14
@Sil3ntKn1ght Can we close this issue?

**Comment by matthuisman** [comment] 2021-06-15 00:33
i found the fix for this just the other day...
**4.10.2202.0 enforces widevine license renewal on non-android platforms.**

Binge needs to renew license every 5mins.
Up until 4.10.2202.0, non-android platforms worked fine and didn't need the renewed license.

However, since 4.10.2202.0 - they do now require it.

Luckily, someone had already PR'd a fix into IA that makes license renewal work correctly on non-android platforms
https://github.com/xbmc/inputstream.adaptive/pull/589
It is live in Inputstream Adaptive 2.6.16 for Matrix

And will be backported to Leia 2.4.8 (https://github.com/xbmc/inputstream.adaptive/pull/711)

**Comment by horstle** [comment] 2021-08-24 15:07
I guess this issue is resolved. If not, feel free to reopen.

**Closed by horstle** 2021-08-24 15:07 UTC
Labels: bug, widevine
