### ISSUE TITLE
InputStreamHelper shows error message when starting Netflix Stream on Kodi 18.9 (Rasberry Pi4)

### ISSUE THREAD

**Issue by BiMaKorn** [emilsvennesson/script.module.inputstreamhelper#504] opened 2022-03-22 19:26 UTC
When starting a Netflix Stream the following error message is shown:
The operation has been canceled.
InputStream Helper has generated an internal error: "Asci" codec can't decode byte 0xe2 in position 58437: ordinal not in range (128).
Please report it to InputStream Helper on GitHub.

InputStream Helper version: 0.5.8
Netfilx version: 1.12.9
Kodi version: 18.9 compiled: 2020-10-24

**Comment by horstle** [comment] 2022-03-22 21:04
Duplicate of #495 

Try the testbuilds from here: https://github.com/emilsvennesson/script.module.inputstreamhelper/issues/497#issuecomment-1068239609

**Closed by horstle** 2022-03-22 21:04 UTC
