### ISSUE TITLE
'ascii' codec can't decode byte 0xc5 in position 29

### ISSUE THREAD

**Issue by Cumol** [emilsvennesson/script.module.inputstreamhelper#333] opened 2020-05-01 08:26 UTC
I am running into the same error as in https://github.com/emilsvennesson/script.module.inputstreamhelper/issues/92

It happens during the extraction of widevine

I am on Kodi 18.6 Git_leia_pi4_18.6-Leia
Inputstream Helper 0.4.6
InputStream adaptive 2.4.4.1

```
2020-05-01 07:18:42.860 T:2573202288   ERROR: [plugin.video.netflix (1)] Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 207, in run
                                                route([part for part in g.PATH.split('/') if part])
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 38, in lazy_login_wrapper
                                                return func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 62, in route
                                                play(videoid=pathitems[1:])
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/common/videoid.py", line 295, in wrapper
                                                return func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/common/logging.py", line 143, in timing_wrapper
                                                return func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/navigation/player.py", line 82, in play
                                                list_item = get_inputstream_listitem(videoid)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/navigation/player.py", line 163, in get_inputstream_listitem
                                                if not is_helper.check_inputstream():
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 407, in check_inputstream
                                                return self._check_drm()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 362, in _check_drm
                                                return self.install_widevine()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 33, in clean_before_after
                                                result = func(self, *args, **kwargs)
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 223, in install_widevine
                                                result = install_widevine_arm(backup_path())
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/widevine/arm.py", line 240, in install_widevine_arm
                                                extract_widevine_from_img(os.path.join(backup_path, arm_device['version']))
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/widevine/arm.py", line 253, in extract_widevine_from_img
                                                for root, _, files in os.walk(mnt_path()):
                                              File "/usr/lib/python2.7/os.py", line 296, in walk
                                              File "/usr/lib/python2.7/os.py", line 296, in walk
                                              File "/usr/lib/python2.7/os.py", line 296, in walk
                                              File "/usr/lib/python2.7/os.py", line 286, in walk
                                              File "/usr/lib/python2.7/posixpath.py", line 73, in join
                                            UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 29: ordinal not in range(128)
```

**Comment by BarmonHammer** [comment] 2020-05-01 08:28
Should be fixed with #330 . I should of posted an issue for it before fixing it, sorry.

**Comment by mediaminister** [comment] 2020-05-01 09:01
Should be fixed by installing this package:
[script.module.inputstreamhelper-0.4.6-unicode-db62fc2.zip](https://github.com/emilsvennesson/script.module.inputstreamhelper/files/4563107/script.module.inputstreamhelper-0.4.6-unicode-db62fc2.zip)

Please report back if this works.

**Comment by fesarlis** [comment] 2020-05-01 09:44
> Should be fixed by installing this package:
> [script.module.inputstreamhelper-0.4.6-unicode-db62fc2.zip](https://github.com/emilsvennesson/script.module.inputstreamhelper/files/4563107/script.module.inputstreamhelper-0.4.6-unicode-db62fc2.zip)
> 
> Please report back if this works.

It does not at least for me. Still the same error.
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 29: ordinal not in range(128)
Please note that I have also tried to downgrade (use version 0.45), and the error still occurs.

**Comment by mediaminister** [comment] 2020-05-01 09:48
This shouldn't occur in v0.4.5, so I guess downgrading failed.

**Comment by fesarlis** [comment] 2020-05-01 10:04
I have tried again with the file you provide. Installed it manually via SSH and of course rebooted. I still get the same error.

Will try again with 0.4.5 and let you know in a couple of minutes.

**Comment by fesarlis** [comment] 2020-05-01 10:16
I can confirm that 0.4.5 works.

**Comment by horstle** [comment] 2020-05-01 10:35
@Cumol @fesarlis Could you confirm whether you have set a custom temporary path or not (possibly with some non-ascii characters)?

**Comment by fesarlis** [comment] 2020-05-01 10:37
Don't even know what you mean :) So I guess not.

**Comment by fesarlis** [comment] 2020-05-01 10:37
Which username?

**Comment by horstle** [comment] 2020-05-01 10:39
If you use LibreELEC/CoreELEC, your username does not contain non-ascii characters (because it's root), not sure about OSMC.

**Comment by fesarlis** [comment] 2020-05-01 10:43
Tell you what. I will do some more tests, and keep this thread open. Will let you know of the outcome with detailed information.

**Comment by mediaminister** [comment] 2020-05-01 12:11
@fesarlis Does this work?
[script.module.inputstreamhelper-0.4.6-unicode-9e7f863.zip](https://github.com/emilsvennesson/script.module.inputstreamhelper/files/4564073/script.module.inputstreamhelper-0.4.6-unicode-9e7f863.zip)

**Comment by Cumol** [comment] 2020-05-01 13:35
I did not set a custom path. Will try with the latest zip file once I am home again.

**Comment by kindzal** [comment] 2020-05-01 14:22
Hi. Can someone advice how to perform a 'clean up' after the widevine installation failure from this issue (remove the chromeos and all temp files, etc.). What is the location of these temp files? This is on Kodi 18.2 LibreElec 9.0.2 RPi2. I don't have much space left after this on SD :). Thanks.

**Comment by kindzal** [comment] 2020-05-01 14:25
> Hi. Can someone advice how to perform a 'clean up' after the widevine installation failure from this issue (remove the chromeos and all temp files, etc.). What is the location of these temp files? This is on Kodi 18 LibreElec 9.2.1 RPi2. I don't have much space left after this on SD :). Thanks.

Ignore this. Performed downgrade of inputstreamhelper to 0.4.5 and widevine installed correctly and cleaned up after itself.

**Comment by mediaminister** [comment] 2020-05-01 15:22
Please test this zip package en report: 
[script.module.inputstreamhelper-0.4.6-unicode-36a0c38.zip](https://github.com/emilsvennesson/script.module.inputstreamhelper/files/4564905/script.module.inputstreamhelper-0.4.6-unicode-36a0c38.zip)

**Comment by Cumol** [comment] 2020-05-01 17:03
The error changed:

```
2020-05-01 17:01:08.799 T:2429805424   ERROR: [plugin.video.netflix (1)] Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 206, in run
                                                route([part for part in g.PATH.split('/') if part])
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 37, in lazy_login_wrapper
                                                return func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 61, in route
                                                play(videoid=pathitems[1:])
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/common/videoid.py", line 295, in wrapper
                                                return func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/common/logging.py", line 143, in timing_wrapper
                                                return func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/navigation/player.py", line 82, in play
                                                list_item = get_inputstream_listitem(videoid)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/navigation/player.py", line 164, in get_inputstream_listitem
                                                raise InputstreamError(common.get_local_string(30046))
                                            InputstreamError: There is a problem with InputStream Adaptive add-on or the Widevine library. May be missing or not enabled, the operation will be cancelled.
```

**Comment by Cumol** [comment] 2020-05-01 17:20
Downgrading to 0.4.5 works though.

**Comment by mediaminister** [comment] 2020-05-01 17:23
I need a [full debug log](https://kodi.wiki/view/Log_file/Easy) to fix this.

**Comment by cesarmacias** [comment] 2020-05-02 05:03
Hello,

The problem persist, I have PI 2 with libreelec 9.2.1, the log debug:

020-05-01 23:48:58.126 T:1639867264   DEBUG: CAddonSettings[script.module.slyguy]: loading setting definitions
2020-05-01 23:48:58.126 T:1639867264   DEBUG: CAddonSettings[script.module.slyguy]: trying to load setting definitions from old format...
2020-05-01 23:48:58.128 T:1639867264   DEBUG: CAddonSettings[script.module.slyguy]: loading setting values
2020-05-01 23:48:58.129 T:1639867264   DEBUG: CSettingsManager: requested setting (_fresh) was not found.
2020-05-01 23:48:58.129 T:1639867264   DEBUG: CAddonSettings[script.module.slyguy]: failed to find definition for setting _fresh. Creating a setting on-the-fly...
2020-05-01 23:48:58.129 T:1639867264   DEBUG: CSettingsManager: requested setting (_userdata) was not found.
2020-05-01 23:48:58.129 T:1639867264   DEBUG: CAddonSettings[script.module.slyguy]: failed to find definition for setting _userdata. Creating a setting on-the-fly...
2020-05-01 23:49:03.133 T:1639867264   DEBUG: CAddonSettings[script.module.slyguy]: loading setting definitions
2020-05-01 23:49:03.430 T:1639867264   DEBUG: CAddonSettings[script.module.slyguy]: trying to load setting definitions from old format...
2020-05-01 23:49:03.432 T:1639867264   DEBUG: CAddonSettings[script.module.slyguy]: loading setting values
2020-05-01 23:49:03.433 T:1639867264   DEBUG: CSettingsManager: requested setting (_fresh) was not found.
2020-05-01 23:49:03.433 T:1639867264   DEBUG: CAddonSettings[script.module.slyguy]: failed to find definition for setting _fresh. Creating a setting on-the-fly...
2020-05-01 23:49:03.433 T:1639867264   DEBUG: CSettingsManager: requested setting (_userdata) was not found.
2020-05-01 23:49:03.433 T:1639867264   DEBUG: CAddonSettings[script.module.slyguy]: failed to find definition for setting _userdata. Creating a setting on-the-fly...
2020-05-01 23:49:08.436 T:1639867264   DEBUG: CAddonSettings[script.module.slyguy]: loading setting definitions
2020-05-01 23:49:09.373 T:1639867264   DEBUG: CAddonSettings[script.module.slyguy]: trying to load setting definitions from old format...
2020-05-01 23:49:09.375 T:1639867264   DEBUG: CAddonSettings[script.module.slyguy]: loading setting values
2020-05-01 23:49:09.375 T:1639867264   DEBUG: CSettingsManager: requested setting (_fresh) was not found.
2020-05-01 23:49:09.375 T:1639867264   DEBUG: CAddonSettings[script.module.slyguy]: failed to find definition for setting _fresh. Creating a setting on-the-fly...
2020-05-01 23:49:09.375 T:1639867264   DEBUG: CSettingsManager: requested setting (_userdata) was not found.
2020-05-01 23:49:09.375 T:1639867264   DEBUG: CAddonSettings[script.module.slyguy]: failed to find definition for setting _userdata. Creating a setting on-the-fly...
2020-05-01 23:49:14.379 T:1639867264   DEBUG: CAddonSettings[script.module.slyguy]: loading setting definitions
2020-05-01 23:49:14.379 T:1639867264   DEBUG: CAddonSettings[script.module.slyguy]: trying to load setting definitions from old format...
2020-05-01 23:49:14.381 T:1639867264   DEBUG: CAddonSettings[script.module.slyguy]: loading setting values
2020-05-01 23:49:14.382 T:1639867264   DEBUG: CSettingsManager: requested setting (_fresh) was not found.
2020-05-01 23:49:14.382 T:1639867264   DEBUG: CAddonSettings[script.module.slyguy]: failed to find definition for setting _fresh. Creating a setting on-the-fly...
2020-05-01 23:49:14.382 T:1639867264   DEBUG: CSettingsManager: requested setting (_userdata) was not found.
2020-05-01 23:49:14.382 T:1639867264   DEBUG: CAddonSettings[script.module.slyguy]: failed to find definition for setting _userdata. Creating a setting on-the-fly...
2020-05-01 23:49:19.386 T:1639867264   DEBUG: CAddonSettings[script.module.slyguy]: loading setting definitions
2020-05-01 23:49:19.386 T:1639867264   DEBUG: CAddonSettings[script.module.slyguy]: trying to load setting definitions from old format...
2020-05-01 23:49:19.388 T:1639867264   DEBUG: CAddonSettings[script.module.slyguy]: loading setting values
2020-05-01 23:49:19.389 T:1639867264   DEBUG: CSettingsManager: requested setting (_fresh) was not found.
2020-05-01 23:49:19.389 T:1639867264   DEBUG: CAddonSettings[script.module.slyguy]: failed to find definition for setting _fresh. Creating a setting on-the-fly...
2020-05-01 23:49:19.389 T:1639867264   DEBUG: CSettingsManager: requested setting (_userdata) was not found.
2020-05-01 23:49:19.389 T:1639867264   DEBUG: CAddonSettings[script.module.slyguy]: failed to find definition for setting _userdata. Creating a setting on-the-fly...
2020-05-01 23:49:24.392 T:1639867264   DEBUG: CAddonSettings[script.module.slyguy]: loading setting definitions
2020-05-01 23:49:24.392 T:1639867264   DEBUG: CAddonSettings[script.module.slyguy]: trying to load setting definitions from old format...
2020-05-01 23:49:24.394 T:1639867264   DEBUG: CAddonSettings[script.module.slyguy]: loading setting values
2020-05-01 23:49:24.394 T:1639867264   DEBUG: CSettingsManager: requested setting (_fresh) was not found.
2020-05-01 23:49:24.395 T:1639867264   DEBUG: CAddonSettings[script.module.slyguy]: failed to find definition for setting _fresh. Creating a setting on-the-fly...
2020-05-01 23:49:24.395 T:1639867264   DEBUG: CSettingsManager: requested setting (_userdata) was not found.
2020-05-01 23:49:24.395 T:1639867264   DEBUG: CAddonSettings[script.module.slyguy]: failed to find definition for setting _userdata. Creating a setting on-the-fly...
2020-05-01 23:49:29.398 T:1639867264   DEBUG: CAddonSettings[script.module.slyguy]: loading setting definitions
2020-05-01 23:49:29.398 T:1639867264   DEBUG: CAddonSettings[script.module.slyguy]: trying to load setting definitions from old format...
2020-05-01 23:49:29.400 T:1639867264   DEBUG: CAddonSettings[script.module.slyguy]: loading setting values
2020-05-01 23:49:29.400 T:1639867264   DEBUG: CSettingsManager: requested setting (_fresh) was not found.
2020-05-01 23:49:29.400 T:1639867264   DEBUG: CAddonSettings[script.module.slyguy]: failed to find definition for setting _fresh. Creating a setting on-the-fly...
2020-05-01 23:49:29.400 T:1639867264   DEBUG: CSettingsManager: requested setting (_userdata) was not found.
2020-05-01 23:49:29.400 T:1639867264   DEBUG: CAddonSettings[script.module.slyguy]: failed to find definition for setting _userdata. Creating a setting on-the-fly...
2020-05-01 23:49:34.404 T:1639867264   DEBUG: CAddonSettings[script.module.slyguy]: loading setting definitions
2020-05-01 23:49:34.404 T:1639867264   DEBUG: CAddonSettings[script.module.slyguy]: trying to load setting definitions from old format...
2020-05-01 23:49:34.406 T:1639867264   DEBUG: CAddonSettings[script.module.slyguy]: loading setting values
2020-05-01 23:49:34.406 T:1639867264   DEBUG: CSettingsManager: requested setting (_fresh) was not found.
2020-05-01 23:49:34.406 T:1639867264   DEBUG: CAddonSettings[script.module.slyguy]: failed to find definition for setting _fresh. Creating a setting on-the-fly...
2020-05-01 23:49:34.407 T:1639867264   DEBUG: CSettingsManager: requested setting (_userdata) was not found.
2020-05-01 23:49:34.407 T:1639867264   DEBUG: CAddonSettings[script.module.slyguy]: failed to find definition for setting _userdata. Creating a setting on-the-fly...
2020-05-01 23:49:39.411 T:1639867264   DEBUG: CAddonSettings[script.module.slyguy]: loading setting definitions
2020-05-01 23:49:39.412 T:1639867264   DEBUG: CAddonSettings[script.module.slyguy]: trying to load setting definitions from old format...
2020-05-01 23:49:39.414 T:1639867264   DEBUG: CAddonSettings[script.module.slyguy]: loading setting values
2020-05-01 23:49:39.414 T:1639867264   DEBUG: CSettingsManager: requested setting (_fresh) was not found.
2020-05-01 23:49:39.414 T:1639867264   DEBUG: CAddonSettings[script.module.slyguy]: failed to find definition for setting _fresh. Creating a setting on-the-fly...
2020-05-01 23:49:39.414 T:1639867264   DEBUG: CSettingsManager: requested setting (_userdata) was not found.
2020-05-01 23:49:39.414 T:1639867264   DEBUG: CAddonSettings[script.module.slyguy]: failed to find definition for setting _userdata. Creating a setting on-the-fly...
2020-05-01 23:49:44.418 T:1639867264   DEBUG: CAddonSettings[script.module.slyguy]: loading setting definitions
2020-05-01 23:49:44.418 T:1639867264   DEBUG: CAddonSettings[script.module.slyguy]: trying to load setting definitions from old format...
2020-05-01 23:49:44.421 T:1639867264   DEBUG: CAddonSettings[script.module.slyguy]: loading setting values
2020-05-01 23:49:44.421 T:1639867264   DEBUG: CSettingsManager: requested setting (_fresh) was not found.
2020-05-01 23:49:44.421 T:1639867264   DEBUG: CAddonSettings[script.module.slyguy]: failed to find definition for setting _fresh. Creating a setting on-the-fly...
2020-05-01 23:49:44.421 T:1639867264   DEBUG: CSettingsManager: requested setting (_userdata) was not found.
2020-05-01 23:49:44.421 T:1639867264   DEBUG: CAddonSettings[script.module.slyguy]: failed to find definition for setting _userdata. Creating a setting on-the-fly...
2020-05-01 23:49:49.425 T:1639867264   DEBUG: CAddonSettings[script.module.slyguy]: loading setting definitions
2020-05-01 23:49:51.365 T:1639867264   DEBUG: CAddonSettings[script.module.slyguy]: trying to load setting definitions from old format...
2020-05-01 23:49:51.367 T:1639867264   DEBUG: CAddonSettings[script.module.slyguy]: loading setting values
2020-05-01 23:49:51.367 T:1639867264   DEBUG: CSettingsManager: requested setting (_fresh) was not found.
2020-05-01 23:49:51.367 T:1639867264   DEBUG: CAddonSettings[script.module.slyguy]: failed to find definition for setting _fresh. Creating a setting on-the-fly...
2020-05-01 23:49:51.367 T:1639867264   DEBUG: CSettingsManager: requested setting (_userdata) was not found.
2020-05-01 23:49:51.367 T:1639867264   DEBUG: CAddonSettings[script.module.slyguy]: failed to find definition for setting _userdata. Creating a setting on-the-fly...
2020-05-01 23:49:56.373 T:1639867264   DEBUG: CAddonSettings[script.module.slyguy]: loading setting definitions
2020-05-01 23:49:56.373 T:1639867264   DEBUG: CAddonSettings[script.module.slyguy]: trying to load setting definitions from old format...
2020-05-01 23:49:56.375 T:1639867264   DEBUG: CAddonSettings[script.module.slyguy]: loading setting values
2020-05-01 23:49:56.375 T:1639867264   DEBUG: CSettingsManager: requested setting (_fresh) was not found.
2020-05-01 23:49:56.375 T:1639867264   DEBUG: CAddonSettings[script.module.slyguy]: failed to find definition for setting _fresh. Creating a setting on-the-fly...
2020-05-01 23:49:56.375 T:1639867264   DEBUG: CSettingsManager: requested setting (_userdata) was not found.
2020-05-01 23:49:56.375 T:1639867264   DEBUG: CAddonSettings[script.module.slyguy]: failed to find definition for setting _userdata. Creating a setting on-the-fly...
2020-05-01 23:49:57.339 T:1372578688   DEBUG: [plugin.onedrive][service-export-1372578688]: export_map: {}
2020-05-01 23:50:01.380 T:1639867264   DEBUG: CAddonSettings[script.module.slyguy]: loading setting definitions
2020-05-01 23:50:01.381 T:1639867264   DEBUG: CAddonSettings[script.module.slyguy]: trying to load setting definitions from old format...
2020-05-01 23:50:01.383 T:1639867264   DEBUG: CAddonSettings[script.module.slyguy]: loading setting values
2020-05-01 23:50:01.384 T:1639867264   DEBUG: CSettingsManager: requested setting (_fresh) was not found.
2020-05-01 23:50:01.384 T:1639867264   DEBUG: CAddonSettings[script.module.slyguy]: failed to find definition for setting _fresh. Creating a setting on-the-fly...
2020-05-01 23:50:01.384 T:1639867264   DEBUG: CSettingsManager: requested setting (_userdata) was not found.
2020-05-01 23:50:01.384 T:1639867264   DEBUG: CAddonSettings[script.module.slyguy]: failed to find definition for setting _userdata. Creating a setting on-the-fly...
2020-05-01 23:50:05.449 T:1294979968   ERROR: [script.module.inputstreamhelper] [u'modinfo', u'loop'] cmd failed.
2020-05-01 23:50:05.450 T:1294979968   DEBUG: [script.module.inputstreamhelper] [u'modinfo', u'loop'] cmd output:
                                            modinfo: ERROR: Module loop not found.
2020-05-01 23:50:05.450 T:1294979968   DEBUG: [script.module.inputstreamhelper] loop is built in the kernel.
2020-05-01 23:50:05.581 T:1294979968   DEBUG: [script.module.inputstreamhelper] [u'losetup', u'-f'] cmd executed successfully.
2020-05-01 23:50:05.582 T:1294979968   DEBUG: [script.module.inputstreamhelper] [u'losetup', u'-f'] cmd output:
                                            /dev/loop2
2020-05-01 23:50:05.584 T:1294979968   DEBUG: [script.module.inputstreamhelper] Stored /dev/loop2 in loop_dev
2020-05-01 23:50:05.585 T:1294979968   DEBUG: [script.module.inputstreamhelper] Found free loop device: /dev/loop2
2020-05-01 23:50:06.261 T:1294979968   DEBUG: [script.module.inputstreamhelper] [u'parted', u'-s', u'/storage/.kodi/userdata/addon_data/script.module.inputstreamhelper/temp/chromeos_12739.111.1_bob_recovery_stable-channel_mp.bin', u'unit s print'] cmd executed successfully.
2020-05-01 23:50:06.262 T:1294979968   DEBUG: [script.module.inputstreamhelper] [u'parted', u'-s', u'/storage/.kodi/userdata/addon_data/script.module.inputstreamhelper/temp/chromeos_12739.111.1_bob_recovery_stable-channel_mp.bin', u'unit s print'] cmd output:
                                            Model:  (file)
                                            Disk /storage/.kodi/userdata/addon_data/script.module.inputstreamhelper/temp/chromeos_12739.111.1_bob_recovery_stable-channel_mp.bin: 4534320s
                                            Sector size (logical/physical): 512B/512B
                                            Partition Table: gpt
                                            Disk Flags: 
                                            
                                            Number  Start     End       Size      File system  Name        Flags
                                            11      64s       16447s    16384s                 RWFW
                                             6      16448s    16448s    1s                     KERN-C
                                             7      16449s    16449s    1s                     ROOT-C
                                             9      16450s    16450s    1s                     reserved
                                            10      16451s    16451s    1s                     reserved
                                             2      20480s    53247s    32768s                 KERN-A
                                             4      53248s    86015s    32768s                 KERN-B
                                             8      86016s    118783s   32768s    ext4         OEM
                                            12      249856s   315391s   65536s    fat16        EFI-SYSTEM  boot, esp
                                             5      315392s   319487s   4096s                  ROOT-B
                                             3      319488s   4513791s  4194304s  ext2         ROOT-A
                                             1      4513792s  4534271s  20480s    ext2         STATE
2020-05-01 23:50:06.381 T:1294979968   DEBUG: [script.module.inputstreamhelper] [u'losetup', u'-o', '163577856', u'/dev/loop2', u'/storage/.kodi/userdata/addon_data/script.module.inputstreamhelper/temp/chromeos_12739.111.1_bob_recovery_stable-channel_mp.bin'] cmd executed successfully.
2020-05-01 23:50:06.383 T:1294979968   DEBUG: [script.module.inputstreamhelper] Stored True in attached_loop_dev
2020-05-01 23:50:06.411 T:1639867264   DEBUG: CAddonSettings[script.module.slyguy]: loading setting definitions
2020-05-01 23:50:06.411 T:1639867264   DEBUG: CAddonSettings[script.module.slyguy]: trying to load setting definitions from old format...
2020-05-01 23:50:06.414 T:1639867264   DEBUG: CAddonSettings[script.module.slyguy]: loading setting values
2020-05-01 23:50:06.414 T:1639867264   DEBUG: CSettingsManager: requested setting (_fresh) was not found.
2020-05-01 23:50:06.414 T:1639867264   DEBUG: CAddonSettings[script.module.slyguy]: failed to find definition for setting _fresh. Creating a setting on-the-fly...
2020-05-01 23:50:06.415 T:1639867264   DEBUG: CSettingsManager: requested setting (_userdata) was not found.
2020-05-01 23:50:06.415 T:1639867264   DEBUG: CAddonSettings[script.module.slyguy]: failed to find definition for setting _userdata. Creating a setting on-the-fly...
2020-05-01 23:50:06.418 T:1294979968  NOTICE: [script.module.inputstreamhelper] Recursively create directory '/storage/.kodi/userdata/addon_data/script.module.inputstreamhelper/temp'.
2020-05-01 23:50:06.557 T:1294979968  NOTICE: [script.module.inputstreamhelper] Create directory '/storage/.kodi/userdata/addon_data/script.module.inputstreamhelper/temp/mnt'.
2020-05-01 23:50:06.656 T:1294979968   DEBUG: [script.module.inputstreamhelper] [u'mount', u'-t', u'ext2', u'-o', u'ro', u'/dev/loop2', u'/storage/.kodi/userdata/addon_data/script.module.inputstreamhelper/temp/mnt'] cmd executed successfully.
2020-05-01 23:50:06.659 T:1294979968  NOTICE: [script.module.inputstreamhelper] Recursively create directory '/storage/.kodi/userdata/addon_data/script.module.inputstreamhelper/temp'.
2020-05-01 23:50:06.662 T:1294979968  NOTICE: [script.module.inputstreamhelper] Create directory '/storage/.kodi/userdata/addon_data/script.module.inputstreamhelper/temp/mnt'.
2020-05-01 23:50:07.806 T:1294979968   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeDecodeError'>
                                            Error Contents: 'ascii' codec can't decode byte 0xc5 in position 29: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/default.py", line 8, in <module>
                                                run(sys.argv)
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/api.py", line 14, in run
                                                widevine_install()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/api.py", line 42, in widevine_install
                                                Helper('mpd', drm='widevine').install_widevine()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 33, in clean_before_after
                                                result = func(self, *args, **kwargs)
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 223, in install_widevine
                                                result = install_widevine_arm(backup_path())
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/widevine/arm.py", line 240, in install_widevine_arm
                                                extract_widevine_from_img(os.path.join(backup_path, arm_device['version']))
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/widevine/arm.py", line 253, in extract_widevine_from_img
                                                for root, _, files in os.walk(mnt_path()):
                                              File "/usr/lib/python2.7/os.py", line 296, in walk
                                              File "/usr/lib/python2.7/os.py", line 296, in walk
                                              File "/usr/lib/python2.7/os.py", line 296, in walk
                                              File "/usr/lib/python2.7/os.py", line 286, in walk
                                              File "/usr/lib/python2.7/posixpath.py", line 73, in join
                                            UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 29: ordinal not in range(128)
                                            -->End of Python script error report<--

**Comment by horstle** [comment] 2020-05-02 13:13
@mediaminister The debug log from https://github.com/emilsvennesson/script.module.inputstreamhelper/issues/325#issuecomment-622942291 is a little different. Maybe this gives some new insight?

**Comment by mediaminister** [comment] 2020-05-02 13:43
Meanwhile I know what is needed to fix this. To fully support unicode chars in all paths we need to encode paths to bytestrings when accessing the filesystem. (Because we use `unicode_literals`, there are quite a few adjustments needed.)

**Comment by pfirestone** [comment] 2020-05-02 16:23
Hi, I updated to your 0.4.7 release and I still got an error:

`: -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeDecodeError'>
                                            Error Contents: 'ascii' codec can't decode byte 0xc5 in position 29: ordinal not in range(128)
                                            Traceback (most recent call last):
                                                widevine_install()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/api.py", line 42, in widevine_install
                                                Helper('mpd', drm='widevine').install_widevine()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 33, in clean_before_after
                                                result = func(self, *args, **kwargs)
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 223, in install_widevine
                                                result = install_widevine_arm(backup_path())
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/widevine/arm.py", line 240, in install_widevine_arm
                                                extract_widevine_from_img(os.path.join(backup_path, arm_device['version']))
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/widevine/arm.py", line 253, in extract_widevine_from_img
                                                for root, _, files in os.walk(mnt_path()):
                                              File "/usr/lib/python2.7/os.py", line 296, in walk
                                              File "/usr/lib/python2.7/os.py", line 296, in walk
                                              File "/usr/lib/python2.7/os.py", line 296, in walk
                                              File "/usr/lib/python2.7/os.py", line 286, in walk
                                              File "/usr/lib/python2.7/posixpath.py", line 73, in join
                                            UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 29: ordinal not in range(128)
                                            -->End of Python script error report<--`
Hopefully this helps.

**Comment by mediaminister** [comment] 2020-05-02 17:15
@pfirestone @cesarmacias @fesarlis @Cumol @kindzal @hierklapptnix @cesarmacias @jduffas 
Please test the following zip package en report back if this works: 
- uninstall InputStreamHelper first
- reboot your Kodi device
- install [script.module.inputstreamhelper-0.4.6-unicode-e04d71a.zip](https://github.com/emilsvennesson/script.module.inputstreamhelper/files/4568320/script.module.inputstreamhelper-0.4.6-unicode-e04d71a.zip)

- report back if it fixes this issue or provide a full debug log if the problem persists: https://kodi.wiki/view/Log_file/Easy

**Comment by pfirestone** [comment] 2020-05-02 18:42
It fixed the issue, updated Widevine and successfully played back from Netflix.

**Comment by hierklapptnix** [comment] 2020-05-02 18:50
I checked the zip on my RPi3 system and it does not work. It is still stuck at about 90-95%.
I guess you have to include horstle's unzip changes before I can see your changes because I don't see any '0xc5' in the log. Only with horstle's version I got that far.

I can try to merge his changes into your zip but I'm not sure I will be able to achieve that...

I even downloaded the streamhelper addon from my Pi with scp and compared the files with those of your zip to ensure the installation was correct.

[kodi-develop_0.4.6-unicode-e04d71a.log](https://github.com/emilsvennesson/script.module.inputstreamhelper/files/4568549/kodi-develop_0.4.6-unicode-e04d71a.log)

**Comment by horstle** [comment] 2020-05-02 19:10
I rebased my unzip branch to include the commit from mediaminister. You can download that as a zip (https://github.com/horstle/script.module.inputstreamhelper/archive/unzip.zip) and test it.

**Comment by gurcan97** [comment] 2020-05-02 19:34
Merhaba   pi4 de  silip dosyayı yükleyince normal çalıştı .  Teşekkürler herkese .

**Comment by hierklapptnix** [comment] 2020-05-02 20:24
Ok. horstle's version works on my RPi3 test system. With my RPi4 I'll wait for the 0.4.7. Old Widevine still works and I don't want to delete it, so I can test the update process as well as the fresh install that I tested now.

And I'm proud to say that my self merged version, that I had finished just when I saw that horstle updated his stuff, does the trick, too (allthough the progress-/remain-time was missing).

Thanks for your work!

**Closed** 2020-05-03 15:48 UTC
Labels: arm, bug

**Comment by npmstart-pray** [comment] 2020-05-03 17:27
Everyone in my house is eagerly waiting for v0.4.7.
'sfunny how until we had netflix, nobody wanted netflix.  Thanks for proving me right, CoVid lol

**Comment by shablamy** [comment] 2020-05-03 18:46
> @pfirestone @cesarmacias @fesarlis @Cumol @kindzal @hierklapptnix @cesarmacias @jduffas
> Please test the following zip package en report back if this works:
> 
> * uninstall InputStreamHelper first
> * reboot your Kodi device
> * install [script.module.inputstreamhelper-0.4.6-unicode-e04d71a.zip](https://github.com/emilsvennesson/script.module.inputstreamhelper/files/4568320/script.module.inputstreamhelper-0.4.6-unicode-e04d71a.zip)
> * report back if it fixes this issue or provide a full debug log if the problem persists: https://kodi.wiki/view/Log_file/Easy

Tried this now, still got the same error: https://pastebin.com/m2tXxDvq

**Comment by mediaminister** [comment] 2020-05-03 18:59
Here is the new release: https://github.com/emilsvennesson/script.module.inputstreamhelper/releases/tag/v0.4.7
