### ISSUE TITLE
Unable to calculate partition offset with fdisk -l 

### ISSUE THREAD

**Issue by evrards** [emilsvennesson/script.module.inputstreamhelper#157] opened 2019-09-04 08:34 UTC
Trying to make WidevineCDM work on a Rpi3 running Kodi 18.3, it raises an error when calculating partition offset.

[error_widevine.txt](https://github.com/emilsvennesson/script.module.inputstreamhelper/files/3573497/error_widevine.txt)

Workaround : install "parted" to get the offset calculated by nthis tool, isntead of "fdisk".

**Comment by mediaminister** [comment] 2019-09-04 10:06
This is already fixed in v0.4.2: please update InputStream Helper in Kodi

**Comment by evrards** [comment] 2019-09-04 11:32
Thanks!

**Closed** 2019-09-04 11:31 UTC

**Comment by dagwieers** [comment] 2019-09-04 18:34
This is a duplicate of #146
