### ISSUE TITLE
Function missing required argument 'line1' (pos 2)

### ISSUE THREAD

**Issue by tweimer** [emilsvennesson/script.module.inputstreamhelper#338] opened 2020-05-01 18:41 UTC
Hi,
This error appears every time I try to watch smth.

[log-2020-04-25-19.58.47.zip](https://github.com/emilsvennesson/script.module.inputstreamhelper/files/4565824/log-2020-04-25-19.58.47.zip)

I already opened an issue for that in https://github.com/CastagnaIT/plugin.video.netflix/issues/601, but I got told that it is an error in this project.

> "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/kodiutils.py", line 124, in yesno_dialog

Seems to be a problem with Kodi 19.

**Comment by horstle** [comment] 2020-05-01 19:57
Duplicate of #324 . Solution is to update inputstreamhelper...

**Closed by horstle** 2020-05-01 19:57 UTC

**Comment by tweimer** [comment] 2020-05-01 20:45
Hi,
Well I got this error even with the latest trunk so far. Where can I find a fixed version?

**Comment by dagwieers** [comment] 2020-05-01 20:54
@tweimer You are running an older development Kodi, which is no longer supported by **inputstreamhelper**. Kodi recently went through API changes that broke backward-compatibility and as such we implemented these API changes for Kodi v19, which breaks "older" Kodi v19 releases.

We only support stable releases (and do our best to make things work on the Kodi master branch).

**Comment by tweimer** [comment] 2020-05-01 23:19
@dagwieers Thank you, didn't realize I had to update Libreelec itself.

**Comment by dagwieers** [comment] 2020-05-02 01:02
@tweimer The API breaking changes have taken us by surprise as well. Normally you expect breaking changes to be prepared and implemented at the start of a new development cycle. Not at the end (I assume Kodi v19 is nearing a beta release).
