### ISSUE TITLE
RPi Netflix addon raises unicode error in InputStream Helper

### ISSUE THREAD

**Issue by jsharples** [emilsvennesson/script.module.inputstreamhelper#502] opened 2022-03-16 09:03 UTC
Last couple of days the Netflix add-on has been throwing an error message in InputStream Helper and failing to play anything.  I'm using a Pi3 Model B, LibreELEC version 9.2.8. InputStream Helper is v0.5.8

Here's the log message.

```
LibreELEC:~ # tail -20 .kodi/temp/kodi.log
2022-03-16 19:42:01.784 T:1412420480  NOTICE: [script.module.inputstreamhelper] Hardlink file '/storage/.kodi/userdata/addon_data/script.module.inputstreamhelper/backup/13505.73.0/config.json' to '/storage/.kodi/cdm/config.json'.
2022-03-16 19:42:25.063 T:1936890304   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
2022-03-16 19:42:33.399 T:1420813184   ERROR: [plugin.video.netflix (3)] Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/navigation/player.py", line 157, in get_inputstream_listitem
                                                inputstream_ready = is_helper.check_inputstream()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 407, in check_inputstream
                                                return self._check_drm()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 359, in _check_drm
                                                return self._check_widevine()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 329, in _check_widevine
                                                self._update_widevine()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 288, in _update_widevine
                                                latest_version = latest_widevine_version()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/widevine/widevine.py", line 164, in latest_widevine_version
                                                devices = chromeos_config()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/widevine/arm.py", line 63, in chromeos_config
                                                return json.loads(http_get(config.CHROMEOS_RECOVERY_URL))
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/utils.py", line 73, in http_get
                                                return content.decode()
                                            UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 58437: ordinal not in range(128)
```

**Comment by horstle** [comment] 2022-03-16 09:21
Another duplicate of #495

**Closed by horstle** 2022-03-16 09:21 UTC
